name: CI

on:
    push:
        branches: ["main"]

permissions:
  id-token: write
  contents: read
jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

              
            - name: Test
              run: dotnet test --configuration Release --no-build


                            
            - name: Publish
              run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

            - uses: actions/upload-artifact@v4
              with:
                name: artifact-upload
                path: artifacts/ 
    deploy_dev:
      name: CD
      runs-on: ubuntu-latest
      needs: build

      steps:

        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{secrets.AZURE_TENANT_ID }}

        - uses: actions/download-artifact@v4
          with:
            name: artifact-download
            path: artifacts/ 

        - name: 'Run Azure webapp deploy action using publish profile credentials'
          uses: azure/webapps-deploy@v2
          with: 
            app-name: app-github-actions-azeemyousaf-dev
            package: artifacts/
