name: CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

              
            - name: Test
              run: dotnet test --configuration Release --no-build


                            
            - name: Publish
              run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

            - uses: actions/upload-artifact@v4
              with:
                name: artifact-upload
                path: artifacts/ 